#!/bin/bash
echo "=== Команды для проверки сервера ==="
echo ""
echo "1. Подключитесь к серверу по SSH:"
echo "   ssh u3156202_deploy@server295.hosting.reg.ru"
echo ""
echo "2. Проверьте, запущен ли Node.js:"
echo "   ps aux | grep node"
echo ""
echo "3. Проверьте структуру каталогов:"
echo "   pwd"
echo "   ls -la"
echo ""
echo "4. Проверьте, есть ли server.js:"
echo "   ls -la | grep server"
echo ""
echo "5. Проверьте, есть ли .env файл:"
echo "   ls -la .env"
echo ""
echo "6. Проверьте порты:"
echo "   netstat -tlnp 2>/dev/null | grep LISTEN"
echo ""
echo "7. Проверьте версию Node.js (если доступна):"
echo "   node --version"
echo "   npm --version"
echo ""
echo "8. Проверьте логи (если есть):"
echo "   ls -la *.log"
echo "   tail -50 *.log 2>/dev/null"
